services:

  frontend:
    build: ./frontend

  product-service:
    build: ./product-service

  cart-service:
    build: ./cart-service

  nginx:
    image: nginx:alpine

    ports:
      - "80:80"

    volumes:
      - ./nginx:/etc/nginx

    depends_on:
      - frontend
      - product-service
      - cart-service

  prometheus:
    image: prom/prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./monitoring:/etc/prometheus

  grafana:
    image: grafana/grafana

    ports:
      - "3000:3000"

    depends_on:
      - prometheus