events {}

http {

    upstream frontend {
        server frontend:80;
    }

    upstream product_service {
        server product-service:5001;
    }

    upstream cart_service {
        server cart-service:5002;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://frontend;
        }

        location /products {
            proxy_pass http://product_service;
        }

        location /cart {
            proxy_pass http://cart_service;
        }
    }
}